description = 'CPU-bound dispatcher that pins each Actor to a dedicated spinning thread for ultra-low-latency, deterministic processing.'

dependencies {
    implementation project(':bufferfly-core')
    implementation 'org.jctools:jctools-core:4.0.7'
    implementation 'net.openhft:affinity:3.23.3'


    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly   'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.awaitility:awaitility:4.3.0'
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
        showStandardStreams = false
    }
}
